version: '3.8'

services:
  aethir-checker:
    build: .
    container_name: aethir-checker
    privileged: true
    cgroupns: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /run/lock
      - /tmp
      - /var/log/journal
    restart: unless-stopped
    environment:
      - TZ=UTC
      - container=docker
    # Uncomment if you need to expose ports
    # ports:
    #   - "8080:8080"
    # Uncomment if you need to mount additional volumes
    # volumes:
    #   - ./data:/home/aethir/.aethir
    healthcheck:
      test: ["CMD", "systemctl", "is-active", "aethir-checker"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
